name: Checking and testing

on:
  push:
  pull_request:

jobs:
  type_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests types-requests mypy
      - name: Type checking
        run: mypy main.py

