name: Koala hacker news
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: run
        run: python main.py
      - name: commit change data
        uses: fnkr/github-action-git-bash@v1
        with:
          secrets: |
            ${{ secrets.TOKEN }}
          args: |
            bash -c "$(git rev-parse --abbrev-ref HEAD)" = "main"
            rm -rf .github
            git add -A .github
            git commit -m "Remove .github"
            git remote add origin https://github.com/ZutJoe/Koala_hacker_news.git
            git push --force origin main
