name: Koala hacker news
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: run
        run: python main.py
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - name: Fetch resources
        run: ./scripts/fetch-resources.sh

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            README.md
            data.json
          commit-msg: Update resources
          github-token: ${{ secrets.TOKEN }}
