name: Koala hacker news
on: 
  push:
    branches: main
  schedule: 
    - cron: '0 0 * * TUE'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: run
        run: python main.py
      - name: git
        run: |
          git config --global user.email "zhout50@163.com"
          git config --global user.name "ZutJoe"
          git add .
          git commit -m "${{ steps.date.outputs.date }} update"
          git push
