name: Koala hacker news
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: run
        run: python main.py
      - name: commit change data
        uses: fnkr/github-action-git-bash@v1
        with:
          secrets: |
            ${{ secrets.TOKEN }}
          args: |
            git config --global --add safe.directory /github/workspace
            "bash" "-c" "{ [ \"$(git rev-parse --abbrev-ref HEAD)\" = \"master\" ] || exit 78; } && rm -rf .github && git add -A .github && git commit -m \"Remove .github\" && git remote set-url origin git@github.com:GITHUB/PROJECT.git && git push --force origin master"
