name: Koala hacker news
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: run
        run: python main.py
      - uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          path: |
            README.md
            data.json
          content: 'Updated by update-file action'
