name: Koala hacker news
on:
  push: 
    branches: main
  schedule:
    - cron: '0 14 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: run
        run: python main.py
      - name: Get current date
        id: date
        run: echo "current_date=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: git
        run: |
          git config --global user.email "zhout50@163.com"
          git config --global user.name "ZutJoe"
          git add .
          git commit -m "${{ steps.date.outputs.current_date }} update"
          git push
